version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: host.docker.internal
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
  python:
    build:
      context: ./script/python
      dockerfile: Dockerfile
    container_name: python_env
    command: bash
    tty: true