name: library-db Python

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/library-db-python.yaml"
      - "library-db/mysql"
      - "!library-db/mysql/**.md"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test with pytest on container
      working-directory: library-db/mysql
      run: |
        docker-compose up --build -d db python
        docker exec -w /script/python python_env pytest
