name: Python application

on:
  push:
    branches: [ main ]
    paths:
      - "library-db/mysql"
      - "!library-db/mysql/**.md"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up test DB
      working-directory: library-db/mysql
      run: |
        docker compose up --build -d db
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Test with pytest
      working-directory: library-db/mysql/script/python
      run: |
        python3 -m pytest
